source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.1'
gem 'bootstrap-sass', '3.0.2.1'
gem 'bootswatch-rails', :git => 'https://github.com/log0ymxm/bootswatch-rails'
gem 'sass-rails', '4.0.1'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.0.4'
gem 'turbolinks', '1.1.1'
gem 'jbuilder', '1.0.2'
gem 'pg', '0.15.1'
gem 'httparty', '0.12.0'
gem 'rails-i18n', '4.0.1'
gem 'jquery-turbolinks', '2.0.2'

group :development, :test do
  gem 'rspec-rails', '2.13.1'
end

group :test do
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara', '2.1.0'
end
